services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: database
      KC_DB_URL_DATABASE: maintmanager
      KC_DB_PASSWORD: postgres
      KC_DB_USERNAME: postgres
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8890:8080
    depends_on:
      database:
        condition: service_healthy
    networks:
      - local-keycloak
  database:
    image: postgres
    command: postgres -c 'max_connections=200'
    ports:
      - 5001:5432/tcp
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maintmanager
    healthcheck:
      test: exit 0
    networks:
      - local-keycloak
volumes:
  pgdata:
networks:
  local-keycloak:
    driver: bridge
