spring:
  devtools:
    add-properties: false
  reactor:
    debug-agent:
      enabled: true
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

resilience4j:
  circuitbreaker:
    instances:
      maint-manager:
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 1000ms