spring:
  devtools:
    add-properties: false
  reactor:
    debug-agent:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      maint-manager:
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 1000ms