spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    table: flyway_schema_history
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    url: jdbc:postgresql://localhost:5001/maintmanager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      connection-timeout: 30000
      max-lifetime: 2000000
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: alpha
    disable-swagger-default-url: true
    path: /swagger-ui.html
server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8890
  realm: Myrealm
  resource: login
  public-client: true

logging:
  level:
    org.springframework.security: DEBUG


