openapi: 3.0.0
info:
  title: Maint manager Open API
  description: Maint manager tickets handler [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: Main server
paths:
  /maints:
    get:
      summary: Returns a list of maints.
      description: Returns a list of maints.
      responses:
        '200':
          description: A JSON array of GetMaintResponseDto class
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      format: int64
                      example: 1
                    maintIdentifier:
                      type: string
                      example: MAINT-1
                    capabilityId:
                      todo